version: '2.2'
services:
    mysql:
        image: mysql:5.6
        platform: linux/amd64
        restart:
            always
        ports:
              - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ctldbpw
            MYSQL_DATABASE: ctldb
            MYSQL_USER: ctldb
            MYSQL_PASSWORD: ctldbpw
