name: build
on:
  - push
jobs:
  build:
    name: Executes a full build
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.6
        env:
          MYSQL_ROOT_PASSWORD: ctldbpw
          MYSQL_DATABASE: ctldb
          MYSQL_USER: ctldb
          MYSQL_PASSWORD: ctldbpw
        ports:
          - 3306:3306

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup go 1.13
        uses: actions/setup-go@v3
        with:
            go-version: 1.13

      - name: Deps
        run: |
          make deps

      - name: Test
        run: |
          make test

      - name: Run Snyk
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --fail-on=upgradable

      - name: build
        run: |
          make build